# Copyright (c) 2025 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Configure NuGet for Github
# Based on a snippet in the packages documentation
author: Donal Fellows
description: >
  This configures NuGet so that it can access the organisation namespace for packages.
branding:
  icon: package
  color: green
inputs:
  namespace:
    description: The namespace to access or publish into.
    required: false
    default: ${{ github.repository_owner }}
  short-handle:
    description: The name of the short handle to associated with the Github-hosted repository
    required: false
    default: github
runs:
  using: composite
  steps:
    - name: ensure org name in url is lower case
      id: naming
      shell: python
      run: |
        import os, sys
        name = os.environ["NGNS"].lower()
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
          f.write(f"url=https://nuget.pkg.github.com/{name}/index.json\n")
      env:
        NGNS: ${{ inputs.namespace }}
    - name: configure nuget
      shell: bash
      run: |
        dotnet nuget add source --username "$NGUSER" --password "$NGPASS" --store-password-in-clear-text --name "$NGHNDL" "$NGURL"
      env:
        NGUSER: ${{ github.actor }}
        NGPASS: ${{ secrets.GITHUB_TOKEN }}
        NGURL: ${{ steps.naming.outputs.url }}
        NGHNDL: ${{ inputs.short-handle }}
