# Copyright (c) 2020-2025 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check Copyrights
author: Donal Fellows
description: >
  Uses Apache RAT to check for files without license declarations.
inputs:
  version:
    description: The version of Apache RAT to use.
    required: false
    default: "0.15"
  mirror:
    description: >
      The mirror of the Apache download site to get the library from.
      Example: `https://www.mirrorservice.org/sites/ftp.apache.org/`
    required: false
    default: https://www.apache.org/dyn/closer.cgi?action=download&filename=
    # Another alternative: https://www.mirrorservice.org/sites/ftp.apache.org/
  profile:
    description: |
      Which profile to use. Leave blank to allow any standard license
      (or your own configuration file).
      The profile decides which license(s) are acceptable.

      Known profiles:
        `ASL` - Apache Software License 2.0
        `BSD` - Apache Software License 2.0
        `GPL3` - GNU General Public License version 3
        `MIT` - Apache Software License 2.0
    required: false
  config-file:
    description: |
      Which xml config file to use.

      Supported options are:
        `rat.xml` - All licenses acceptable to RAT (default)
        `rat_asl20.xml` - Only the AppliedApacheSoftwareLicense20 (prefer `profile: ASL`)
        `rat_gpl3.xml` - Only the GNU General Public License version 3 (prefer `profile: GPL3`)
      
      You may also specify an ANT config file yourself.
      This is only useful when developing a new profile. 
    required: false
    default: "rat.xml"
  excludes-file:
    description: >
      The name of the file describing what files should not be checked.
      Defaults to the `.ratexcludes` file in the root of your project.
    required: false
    default: ".ratexcludes"
branding:
  icon: search
  color: red

runs:
  using: composite
  steps:
    - name: Cache RAT
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ github.action_path }}/apache-rat-${{ inputs.version }}
        key: apache-rat-${{ inputs.version }}
    - name: Download RAT
      if: steps.cache.outputs.cache-hit != 'true'
      run: $GITHUB_ACTION_PATH/download.bash
      shell: bash
      env:
        RAT_VERSION: ${{ inputs.version }}
        RAT_MIRROR: ${{ inputs.mirror }}
    - name: Locate files
      id: files
      run: $GITHUB_ACTION_PATH/files.bash
      shell: bash
      env:
        EXCLUDES: ${{ inputs.excludes-file }}
        THE_PROFILE: ${{ inputs.profile }}
        CFG: ${{ inputs.config-file }}
    - name: Check
      run: ant -e -q -f "$CFG" -lib "$LIB" rat
      shell: bash
      env:
        CFG: ${{ steps.files.outputs.config }}
        LIB: ${{ github.action_path }}/apache-rat-${{ inputs.version }}
        EXCLUDES: ${{ steps.files.outputs.excludes }}
