name: Instantiate value as file
description: >
  Instantiates a value (presumably a secret) as a temporary file.
  This action is careful to delete the file later in the workflow (after it shouldn't be required any more).
author: Donal Fellows
branding:
  icon: file-plus
  color: gray-dark
inputs:
  value:
    description: The value to instantiate.
    required: true
  filename:
    description: The file to write to. If unspecified, a temporary file is used.
    required: false
  base64:
    description: If `true`, the value should be base64-decoded before being written to the file.
    required: false
    default: "false"
outputs:
  filename:
    description: The full name of the file that the value was written to.
runs:
  using: node20
  main: main.js
  post: main.js
