# Copyright (c) 2020-2025 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Install Debian/Ubuntu packages"
author: Donal Fellows
description: Runs apt-get to install Debian/Ubuntu packages.
branding:
  color: gray-dark
  icon: download
inputs:
  packages:
    description: The names of the packages to install.
    required: true
runs:
  using: composite
  steps:
  - name: issue warning on wrong platform
    if: runner.os != 'Linux'
    shell: bash
    run: echo "::warning title=Wrong Platform::Cannot run apt-get on non-Linux platforms."
  - name: update
    if: runner.os == 'Linux' && env.uomRIT_aptget_update != 'done'
    shell: bash
    env:
      CFGFILE: ${{ github.action_path }}/apt.conf
    run: exec bash $GITHUB_ACTION_PATH/update.bash
  - name: install packages
    if: runner.os == 'Linux'
    shell: bash
    env:
      PACKAGES: ${{ inputs.packages }}
      CFGFILE: ${{ github.action_path }}/apt.conf
    run: sudo apt-get -c "$CFGFILE" install $PACKAGES
