# Copyright (c) 2025 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Internal: Checkout Self"
description: >
  Checks out this repository.
inputs:
  path:
    description: Where to put the checkout.
    required: true
  sparse-checkout:
    description: What part of the repository to check out.
    required: true
  repository:
    description: What repository to check out.
    default: ${{ github.action_repository }}
  ref:
    description: What ref to check out.
    default: ${{ github.action_ref }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        path: ${{ inputs.path }}
        sparse-checkout: ${{ inputs.sparse-checkout }}
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        persist-credentials: false
