# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: 'REUSE Compliance Check'
description: "Check your project's REUSE compliance for clear and simple licensing and copyright!"
author: 'Free Software Foundation Europe (FSFE)'
inputs:
  args:
    description: "The arguments to pass to the reuse-tool"
    required: true
  branch:
    description: "The branch to check out the reuse-tool from"
    required: false
    default: "main"
runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      path: reuse-tool
      repository: UoMResearchIT/reuse-tool
      ref: ${{ inputs.branch }}

  - name: Setup Environment
    uses: getsentry/action-setup-venv@v2.1.0
    with:
      python-version: 3.12
      cache-dependency-path: |
        reuse-tool
      venv-dir: reuse-tool-venv
      install-cmd: |
        pip install poetry~=1.3.0
        cd reuse-tool
        poetry install --no-interaction --only main
        poetry build --no-interaction
        pip install dist/*.whl

  - name: Run reuse
    shell: bash
    run: |
      source reuse-tool-venv/bin/activate
      reuse ${{ inputs.args }}
