name: Download File
author: Donal Fellows
description: >
  Downloads a file from a URL, using a cached version if possible.
branding:
  color: green
  icon: download
inputs:
  url:
    description: The URL to download from.
    required: true
  local-name:
    description: The local file name. Derived from the URL if not given.
    required: false
  wget-options:
    description: Additional options to pass to `wget`.
    required: false
outputs:
  filename:
    description: The full path to the file.
    value: ${{ steps.filename.outputs.file }}
runs:
  using: composite

  steps:
    - name: Generate target filename
      id: filename
      shell: bash
      run: exec bash $GITHUB_ACTION_PATH/generate.bash
      env:
        URL: ${{ inputs.url }}
        LOCALNAME: ${{ inputs.local-name }}
    - name: Check cache
      id: cache
      uses: actions/cache@v4
      with:
        key: download-${{ inputs.url }}
        path: ${{ steps.filename.outputs.file }}
    - name: Do download
      if: steps.cache.outputs.cache-hit != 'true' && runner.os != 'Windows'
      shell: bash
      run: wget --config=$GITHUB_ACTION_PATH/wgetrc -O "$FILE" $OPTIONS -- "$URL" 
      env:
        URL: ${{ inputs.url }}
        FILE: ${{ steps.filename.outputs.file }}
        OPTIONS: ${{ inputs.wget-options }}
    - name: Do download
      if: steps.cache.outputs.cache-hit != 'true' && runner.os == 'Windows'
      shell: pwsh
      run: ${{ github.action_path }}/runwget.ps1
      env:
        URL: ${{ inputs.url }}
        FILE: ${{ steps.filename.outputs.file }}
        OPTIONS: ${{ inputs.wget-options }}
