# Copyright (c) 2025 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow adds a PR to a project.
# To re-use in your repo:
#
# name: Add PRs to Project
# on:
#   pull_request:
#     types:
#       - review_requested
# jobs:
#   call-add-prs-to-project:
#     uses: UoMResearchIT/Actions/.github/workflows/add_prs_to_project.yml@v1.2.6
#     with:
#       project-number: 123
#     secrets:
#       bot-key: ${{ secrets.ORG_ACTIONS_BOT_PRIVATE_KEY }}
#

name: Add PR to project
run-name: "Add PR #${{ github.event.pull_request.id }} to Project #${{ inputs.project-number }}"
on:
  workflow_call:
    inputs:
      project-number:
        type: number
        required: true
        description: >
          The identifier of the project to add the PR to.
      status-field:
        type: string
        required: false
        default: Status
        description: >
          The name of the "Status" field, in case that is something other than the default.
      target-status:
        type: string
        required: false
        default: Ready To Review
        description: >
          The name of the option to select in as the Status field.
          This workflow assumes that the project has a single select field called "Status" (or whatever the status_field input names it as) that includes an option that this value specifies.
    secrets:
      bot-key:
        description: The ORG_ACTIONS_BOT_PRIVATE_KEY from the organisation secrets.
        required: true

jobs:
  track_pr:
    name: Add PR
    runs-on: ubuntu-latest
    steps:
      - name: Create Github App Token
        id: mint-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.ORG_ACTIONS_BOT_APP_ID }}
          private-key: ${{ secrets.bot-key }}
          owner: ${{ github.repository_owner }}
          permission-organization-projects: write
        timeout-minutes: 1
      - name: Add PR to Project
        uses: UoMResearchIT/actions/add-pr-to-project@add-pr-to-project-action
        with:
          organisation: ${{ github.repository_owner }}
          pr-number: ${{ github.event.pull_request.node_id }}
          project-number: ${{ inputs.project-number }}
          status-field: ${{ inputs.status-field }}
          target-status: ${{ inputs.target-status }}
          token: ${{ steps.mint-token.outputs.token }}
